sudo: required
services:
  - docker

before_install: 
  - docker build -t samuelhenriquebr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true samuelhenriquebr/react-test npm test -- --coverage

after_success: 
  - docker build -t samuelhenriquebr/multi-client ./client
  - docker build -t samuelhenriquebr/multi-nginx ./nginx
  - docker build -t samuelhenriquebr/multi-server ./server
  - docker build -t samuelhenriquebr/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push samuelhenriquebr/multi-client
  - docker push samuelhenriquebr/multi-nginx
  - docker push samuelhenriquebr/multi-server
  - docker push samuelhenriquebr/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-461596899094"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY